### ISSUE TITLE
Pics for readme

### ISSUE THREAD

**Issue by iKusii** [sopra-fs23-group-28/sopra-fs23-group-28-client#30]
![1](https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/assets/74095071/f6a6a635-8c39-4178-abc3-b8e6769f54eb)

![2](https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/assets/74095071/fcef6f6a-2676-4322-90f2-08becac2a1f0)

![3](https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/assets/74095071/950e9ed5-3ea7-4dfb-a2c1-48241d285baa)

![4](https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/assets/74095071/3511e733-9baf-485e-ae4a-b5e41325ef1b)

**Comment by Elyisha** [comment]
![image](https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/assets/116687078/ea6e6179-7858-4134-b960-9e54dda111ba)

**Comment by samuelfrnk** [comment]
![image](https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/assets/93734771/9ce93d53-6e72-4ec3-a42b-3fc99485a6a2)

**Comment by iKusii** [comment]
done
